### ISSUE TITLE
md5sum is wrong

### ISSUE THREAD

**Issue by dagodax** [KaOS-Community-Packages/brave#1]
[dago@kaos brave]$ makepkg -s
==> Creando el paquete: brave 0.9.2-1 (jue abr 21 23:54:30 ART 2016)
==> Comprobando dependencias mientras se ejecuta…
==> Comprobando dependencias mientras se compila…
==> Recibiendo las fuentes…
  -> Descargando brave_0.9.2_amd64.deb…
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   598    0   598    0     0    768      0 --:--:-- --:--:-- --:--:--   767
100 51.8M  100 51.8M    0     0  1611k      0  0:00:32  0:00:32 --:--:-- 1747k
==> Validando los archivos source con md5sums…
    brave_0.9.2_amd64.deb ... HA FALLADO
==> ERROR: ¡Uno o más archivos no superaron el control de validación!
[dago@kaos brave]$ ls
src/  brave_0.9.2_amd64.deb  PKGBUILD  README.md
[dago@kaos brave]$ makepkg -g
==> Recibiendo las fuentes…
  -> brave_0.9.2_amd64.deb ha sido encontrado 
==> Generando las sumas de control para los archivos fuentes…
md5sums=('f0ec1378848d0dcae7506c1592be2863')

**Comment by forostm** [comment]
fixed in [9bdaeb](https://github.com/KaOS-Community-Packages/brave/commit/9bdaeb8afc221432debbcb212c4964f58a353e09)
